[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Runtime API definition required by fee-market RPC extensions."
edition     = "2021"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "pallet-fee-market-rpc-runtime-api"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-bridges-substrate"
version     = "0.1.0"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "3.0", default-features = false }
serde = { version = "1.0", optional = true, features = ["derive"] }
# paritytech
bp-messages = { default-features = false, path = "../../../../primitives/messages" }
sp-api      = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime  = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sp-std      = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }

[features]
default = ["std"]

std = [
	# crates.io
	"codec/std",
	"serde",
	# paritytech
	"bp-messages/std",
	"sp-api/std",
	"sp-std/std",
	"sp-runtime/std",
]
