[package]
name = "relay-bridge-hub-westend-client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true

[lints]
workspace = true

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }
subxt = { workspace = true }

# Bridge dependencies

bp-bridge-hub-westend = { workspace = true }
bp-header-chain = { workspace = true }
bp-messages = { workspace = true }
bp-polkadot-core = { workspace = true }
bp-runtime = { workspace = true }

relay-substrate-client = { workspace = true }

# Substrate Dependencies

sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-weights = { workspace = true }

[dev-dependencies]
bp-runtime = { workspace = true }
sp-consensus-grandpa = { workspace = true }
