# Exposed ports: 10616, 10617

version: '3.5'
services:
  relay-headers-westend-to-millau-1:
    image: paritytech/substrate-relay
    entrypoint: /entrypoints/relay-headers-westend-to-millau-entrypoint.sh
    volumes:
      - ./bridges/westend-millau/entrypoints:/entrypoints
    environment:
      RUST_LOG: rpc=trace,bridge=trace
    ports:
      - "10616:9616"
    depends_on:
      - millau-node-alice

  relay-headers-westend-to-millau-2:
    image: paritytech/substrate-relay
    entrypoint: /entrypoints/relay-headers-westend-to-millau-entrypoint.sh
    volumes:
      - ./bridges/westend-millau/entrypoints:/entrypoints
    environment:
      RUST_LOG: rpc=trace,bridge=trace
      EXT_RELAY_ACCOUNT: //Harry
    ports:
      - "10617:9616"
    depends_on:
      - millau-node-alice

  # Note: These are being overridden from the top level `monitoring` compose file.
  grafana-dashboard:
    environment:
      VIRTUAL_HOST: grafana.millau.brucke.link,grafana.rialto.brucke.link
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: grafana.millau.brucke.link,grafana.rialto.brucke.link
      LETSENCRYPT_EMAIL: admin@parity.io
    volumes:
      - ./bridges/westend-millau/dashboard/grafana:/etc/grafana/dashboards/westend-millau:ro

  prometheus-metrics:
    volumes:
      - ./bridges/westend-millau/dashboard/prometheus/targets.yml:/etc/prometheus/targets-westend-millau.yml
    depends_on:
      - relay-headers-westend-to-millau
